apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30082
  target:
    kind: Service
    name: kargo-demo
images:
- name: mosheeven397/webapp
  newName: mosheeven397/webapp
  newTag: 0.0.1
